apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
    - host: grafana.jack-newbury.co.uk
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
